### Review Request Charter

- [ ] I've tested this locally during the run and build time and am confident that my changes fulfill the requirements of the task.
- [ ] I have added any newly introduced environment variable to the `.env.example` file and added a quick description if they are not self-explanatory.
- [ ] I’ve added a unit/integration/e2e test to support the code changes.
- [ ] I've ensured no logs transmit any user-sensitive data (HIPAA Compliance).
- [ ] All acceptance criteria outlined in the ticket are accomplished.
- [ ] I have added a meaningful title.
- [ ] I have added a meaningful description.


### Description
